[project]
name = "fastapi-tdd-docker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.115.12",
    "numpy>=2.3.4",
    "pydantic>=2.11.9",
    "pydantic-settings==2.8.1",
    "uvicorn==0.34.1",
]
